"""Three-inventory API (copy / rewrite / scan) — Task 6, Decision D3.

``copy_paths``: everything git lists (tracked + non-ignored untracked),
minus ``.git``, RETAINING symlinks and gitlinks (type-tagged via
``PathEntry.kind``). ``rewrite_paths``: thin named wrapper on
``iter_target_files`` (already lockfile- and ``ROOT_CONTROL``-exclusive).
``scan_paths``: copy minus ``ROOT_CONTROL``, minus lockfiles that are BOTH
regenerated by this target's rules AND exempted by the tool's OWN
``DEFAULT_RULES.exclude_files`` (EMP-01 — a target's ``extra_exclude_files``
must never be able to hide content from the no-leak scan), minus
``verify_ignore`` dirs.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

from template_press.rebrand import engine
from template_press.rebrand.engine import (
    ROOT_CONTROL,
    PathEntry,
    copy_paths,
    iter_target_files,
    rewrite_paths,
    scan_paths,
)
from template_press.rebrand.rules import DEFAULT_RULES, load_rules

from .conftest import requires_symlink


def _git(repo: Path, *args: str) -> None:
    subprocess.run(  # noqa: S603
        ["git", "-C", str(repo), *args],  # noqa: S607
        check=True,
        capture_output=True,
    )


def _rev_parse_head(repo: Path) -> str:
    result = subprocess.run(  # noqa: S603
        ["git", "-C", str(repo), "rev-parse", "HEAD"],  # noqa: S607
        check=True,
        capture_output=True,
        encoding="utf-8",
    )
    return result.stdout.strip()


def _rels(entries: list[PathEntry]) -> set[str]:
    return {e.rel.as_posix() for e in entries}


def _kinds(entries: list[PathEntry]) -> dict[str, str]:
    return {e.rel.as_posix(): e.kind for e in entries}


def _build_inventory_target(src_target: Path, tmp_path: Path) -> Path:
    """``src_target`` extended with a lockfile pair, a forced-add ignored
    file, a root control artifact, and a real gitlink — all committed.

    The gitlink is staged LAST via ``git update-index --add --cacheinfo``
    (a fresh ``git add -A`` afterwards would re-stage it as a deletion,
    since its "sub" path has no corresponding working-tree directory —
    confirmed empirically before writing this fixture).
    """
    (src_target / "uv.lock").write_text("version = 1\n", encoding="utf-8")
    (src_target / "bun.lock").write_text('{"lockfileVersion": 0}\n', encoding="utf-8")
    with (src_target / ".gitignore").open("a", encoding="utf-8") as f:
        f.write("secret.env\n")
    (src_target / "secret.env").write_text("TOKEN=shh\n", encoding="utf-8")
    _git(src_target, "add", "-A")
    _git(src_target, "add", "-f", "secret.env")

    control = src_target / "press"
    control.mkdir(exist_ok=True)
    (control / "press-source.toml").write_text(
        '[identity]\npackage_name = "demo_widget"\nowner = "demolabs"\n',
        encoding="utf-8",
    )
    _git(src_target, "add", "-A")
    _git(
        src_target, "commit", "-q", "-m", "add lockfiles, ignored secret, control file"
    )

    inner = tmp_path / "inner"
    inner.mkdir()
    _git(inner, "init", "-q", "-b", "main")
    _git(inner, "config", "user.email", "test@example.com")
    _git(inner, "config", "user.name", "Test")
    (inner / "f.txt").write_text("x\n", encoding="utf-8")
    _git(inner, "add", "-A")
    _git(inner, "commit", "-q", "-m", "inner init")
    sha = _rev_parse_head(inner)

    _git(src_target, "update-index", "--add", "--cacheinfo", f"160000,{sha},sub")
    _git(src_target, "commit", "-q", "-m", "add gitlink sub")
    return src_target


def test_copy_paths_retains_bun_and_uv_lock(src_target: Path, tmp_path: Path):
    target = _build_inventory_target(src_target, tmp_path)
    rels = _rels(copy_paths(target))
    assert "bun.lock" in rels
    assert "uv.lock" in rels


def test_scan_paths_exempts_regenerated_uv_lock_but_not_bun_lock(
    src_target: Path, tmp_path: Path
):
    target = _build_inventory_target(src_target, tmp_path)
    rels = _rels(scan_paths(target, DEFAULT_RULES))
    assert "bun.lock" in rels
    assert "uv.lock" not in rels


def test_scan_paths_regenerate_exemption_keyed_on_tool_not_target(
    src_target: Path,
):
    """EMP-01/F5: a target's press-rules.toml ``regenerate`` must NOT be able to
    scan-exempt a lockfile the tool never regenerates. The exemption requires a
    lockfile to be in BOTH the target's effective ``regenerate`` list AND the
    tool's OWN ``DEFAULT_RULES.regenerate`` (only uv.lock). So a target adding
    ``bun.lock`` cannot blind the no-leak scan to it, while uv.lock — in both
    sets — stays exempt.
    """
    (src_target / "uv.lock").write_text("version = 1\n", encoding="utf-8")
    (src_target / "bun.lock").write_text(
        '{"lockfileVersion": 0, "name": "demo_widget"}\n', encoding="utf-8"
    )
    control = src_target / "press"
    control.mkdir(exist_ok=True)
    (control / "press-rules.toml").write_text(
        '[rules]\nregenerate = ["uv.lock", "bun.lock"]\n', encoding="utf-8"
    )
    _git(src_target, "add", "-A")
    _git(src_target, "commit", "-q", "-m", "add lockfiles + target regenerate override")
    rules = load_rules(src_target)
    assert rules.regenerate == ("uv.lock", "bun.lock")  # target override effective
    rels = _rels(scan_paths(src_target, rules))
    assert "bun.lock" in rels  # NOT exempt — tool has no bun.lock regenerator
    assert "uv.lock" not in rels  # exempt — in BOTH the target's list and tool's


def test_scan_paths_scans_uv_lock_when_target_disables_regenerate(
    src_target: Path,
):
    """F-a: a target that sets ``regenerate = []`` DISABLES uv.lock regen, so
    press neither rewrites it (it is in exclude_files) nor regenerates it — a
    stale source token in uv.lock must therefore be SCANNED, not false-cleaned.
    The exemption requires uv.lock in BOTH the target's effective regenerate
    list AND the tool's regenerable set; an empty target list drops it, so
    keying the exemption on ``DEFAULT_RULES.regenerate`` ALONE was a false clean.
    """
    (src_target / "uv.lock").write_text('name = "demo_widget"\n', encoding="utf-8")
    control = src_target / "press"
    control.mkdir(exist_ok=True)
    (control / "press-rules.toml").write_text(
        "[rules]\nregenerate = []\n", encoding="utf-8"
    )
    _git(src_target, "add", "-A")
    _git(src_target, "commit", "-q", "-m", "disable uv.lock regen; uv.lock leak")
    rules = load_rules(src_target)
    assert rules.regenerate == ()  # target disabled regeneration
    rels = _rels(scan_paths(src_target, rules))
    assert "uv.lock" in rels  # SCANNED — was false-clean under DEFAULT-only keying


def test_scan_paths_excludes_root_control_present_in_copy(
    src_target: Path, tmp_path: Path
):
    target = _build_inventory_target(src_target, tmp_path)
    assert "press/press-source.toml" in ROOT_CONTROL
    assert "press/press-source.toml" in _rels(copy_paths(target))
    assert "press/press-source.toml" not in _rels(scan_paths(target, DEFAULT_RULES))


def test_copy_paths_includes_force_added_gitignored_file(
    src_target: Path, tmp_path: Path
):
    target = _build_inventory_target(src_target, tmp_path)
    assert "secret.env" in _rels(copy_paths(target))


def test_copy_paths_tags_gitlink_kind(src_target: Path, tmp_path: Path):
    target = _build_inventory_target(src_target, tmp_path)
    kinds = _kinds(copy_paths(target))
    assert kinds.get("sub") == "gitlink"


def test_scan_paths_retains_gitlink_entry_type_tagged(src_target: Path, tmp_path: Path):
    target = _build_inventory_target(src_target, tmp_path)
    kinds = _kinds(scan_paths(target, DEFAULT_RULES))
    assert kinds.get("sub") == "gitlink"


@requires_symlink
def test_copy_paths_tags_symlink_kind(src_target: Path):
    link = src_target / "link_to_readme"
    link.symlink_to("README.md")
    _git(src_target, "add", "-A")
    _git(src_target, "commit", "-q", "-m", "add symlink")
    kinds = _kinds(copy_paths(src_target))
    assert kinds.get("link_to_readme") == "symlink"


def test_copy_paths_tags_ordinary_file_kind(src_target: Path):
    kinds = _kinds(copy_paths(src_target))
    assert kinds.get("README.md") == "file"


class _FakeCompleted:
    def __init__(self, stdout: bytes | str):
        self.stdout = stdout
        self.returncode = 0


def _byte_faithful_run(raw: bytes):
    """A ``subprocess.run`` stand-in faithful to real byte/text semantics: in
    text/encoding mode it decodes STRICT and raises ``UnicodeDecodeError`` on
    an invalid byte (the old bug); in byte mode it returns the raw bytes."""

    def fake_run(cmd, *args, **kwargs):
        if kwargs.get("encoding") or kwargs.get("text"):
            return _FakeCompleted(raw.decode(kwargs.get("encoding") or "utf-8"))
        return _FakeCompleted(raw)

    return fake_run


def test_git_listed_decodes_non_utf8_path_bytes_surrogateescape(monkeypatch, tmp_path):
    """F-d: git emits raw path BYTES; a tracked filename with a non-UTF-8 byte
    must decode via surrogateescape instead of crashing enumeration with
    ``UnicodeDecodeError``. macOS/APFS refuses to CREATE such a name, so the raw
    git output is simulated at the subprocess boundary to exercise the decode.
    """
    raw = b"src/demo_widget/bad\xffname.txt\x00README.md\x00"
    monkeypatch.setattr(engine.subprocess, "run", _byte_faithful_run(raw))
    rels = engine._git_listed(tmp_path)  # must not raise
    names = {p.as_posix() for p in rels}
    assert "README.md" in names
    assert any(p.name.startswith("bad") and p.name.endswith("name.txt") for p in rels)


def test_gitlink_rels_decodes_non_utf8_path_bytes_surrogateescape(
    monkeypatch, tmp_path
):
    """F-d: the staged-list (``ls-files --stage``) call must likewise decode raw
    path bytes with surrogateescape so a gitlink whose path carries a non-UTF-8
    byte does not crash enumeration."""
    raw = (
        b"160000 " + b"0" * 40 + b" 0\tbad\xffsub\x00"
        b"100644 " + b"1" * 40 + b" 0\tREADME.md\x00"
    )
    monkeypatch.setattr(engine.subprocess, "run", _byte_faithful_run(raw))
    rels = engine._gitlink_rels(tmp_path)  # must not raise
    assert any(r.startswith("bad") and r.endswith("sub") for r in rels)


def test_rewrite_paths_matches_iter_target_files(src_target: Path):
    expected = {
        p.relative_to(src_target).as_posix()
        for p in iter_target_files(src_target, DEFAULT_RULES)
    }
    actual = {
        p.relative_to(src_target).as_posix()
        for p in rewrite_paths(src_target, DEFAULT_RULES)
    }
    assert actual == expected
